#Site settings
author:      "Antoine TABARAUD"
description: "Personal web site"
title:       "Antoine TABARAUD"
image:       "/assets/img/logo site2.png"
keywords:    "Antoine TABARAUD, TABARAUD, Antoine TBD, AntTBD, Ant TBD"
favicon:     "/assets/img/favicon.ico"

lastUpdate:
    fr:      "janvier 2021"
    en:      "January 2021"

# Build settings
markdown:    kramdown
#permalink:  /projet/:title
