#Site settings
author:        "Antoine TABARAUD"
description:   "Personal web site"
title:         "Antoine TABARAUD"
image:         "logo site2.png"
keywords:      "Antoine TABARAUD, TABARAUD, Antoine TBD, AntTBD, Ant TBD"
favicon:       "favicon.ico"
url:           "https://anttbd.github.io" #"http://localhost"

lastUpdate:
    fr:        "decembre 2021"
    en:        "December 2021"

# Build settings
markdown:      kramdown
#permalink:    /projet/:title
