#Site settings
author:        "Antoine TABARAUD"
description:   "Site vitrine"
title:         "Antoine TABARAUD"
image:         "/assets/img/logo site2.svg"
keywords:      "Antoine TABARAUD, Antoine TBD, AntTBD, Ant TBD"
url:           "https://AntTBD.github.io"

lastUpdate:
    fr:        "septembre 2020"
    en:        "September 2020"

# Build settings
markdown:      kramdown
#permalink:    /projet/:title
